//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Henry_s_Bookstore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTORY
    {
        public string BOOK_CODE { get; set; }
        public int BRANCH_NUM { get; set; }
        public Nullable<int> ON_HAND { get; set; }
    
        public virtual BOOK BOOK { get; set; }
        public virtual BRANCH BRANCH { get; set; }
    }
}
